### ISSUE TITLE
No values displayed at all

### ISSUE THREAD

**Issue by twistedwings** [yaapu/FrskyLuaGCS#12]
![screen-2020-11-06-233951](https://user-images.githubusercontent.com/562809/98417599-89d15700-2081-11eb-9c33-d3d3ae31ee56.jpg)

Radiomaster TX16S
OpenTX 2.3.10
ArduCopter 4.0.5

**Comment by yaapu** [comment]
you need current master, stable releases do not support this yet!

**Comment by drtrigon** [comment]
In which ArduPilot version will it be released?

**Comment by Hwurzburg** [comment]
current 4.1 beta version are out for all vehicles and include this

**Comment by drtrigon** [comment]
Yeah, saw now that beta came yesterday - more or less while I asked... ;) tks!
