### ISSUE TITLE
LuaGCSGUI decimal symbol

### ISSUE THREAD

**Issue by kniuk** [yaapu/FrskyLuaGCS#13]
I live in Poland where separation symbol for decimal is "," instead of "." 
It looks like GUI code relays somehow on decimal symbol in Windows and does not allow to add new parameter unless I change "." to "," in max, min and increment fields.
When I want to change in my param list (lower part of the window) same thing happens - I need to change "." to "," again.

**Comment by yaapu** [comment]
Hi,
not really clear what's going up.
I do a float.tryparse() which relies on culture decimal separator, if you write numbers the way windows expects them, the tryfloat () would succeed, which numbers fails? give a couple examples/screenshots

**Comment by kniuk** [comment]
When numbers are loaded into "Range editor" window they have "." decimal separator, regardless of regional settings.

![Zrzut ekranu 2020-11-30 204814](https://user-images.githubusercontent.com/57300765/100658638-b2323580-334f-11eb-9f01-52bf22b4c974.png)

When clicking Add, Save or even Remove numbers are checked by your function that checks for valid regional separator ("," in my case).

![Zrzut ekranu 2020-11-30 204847](https://user-images.githubusercontent.com/57300765/100658672-bf4f2480-334f-11eb-865b-5d26248ee1db.png)

So before I can click Save I need to edit all "." into ",". 

![Zrzut ekranu 2020-11-30 204912](https://user-images.githubusercontent.com/57300765/100658682-c413d880-334f-11eb-92d9-c9ba0c5aa3f5.png)

Please try to change your windows decimal separator to "," and you will see the red warning because your function expects regional separator, not "."
(You needed to close and reopen LUAGCSGUI for a change to be effective)

P.S. Please remove number checking for Remove button - not needed there.

**Comment by yaapu** [comment]
Hi, I'm Italian my system already has "," as decimal separator (first box at the top)
![image](https://user-images.githubusercontent.com/30294218/100663871-30460a80-3357-11eb-828a-9f5ab452196f.png)

**Comment by yaapu** [comment]
try this one please [LuaGCSGUI_1.13.0.zip](https://github.com/yaapu/FrskyLuaGCS/files/5618731/LuaGCSGUI_1.13.0.zip)

**Comment by kniuk** [comment]
Works! Thanks!
P.S. Great work with lua scripts for ardupilot

**Comment by kniuk** [comment]
Hi, Please change LuaGCSGUI.exe available in main repository (1.0.12.1) to the one attached above (1.0.13.0).

Regards,
Jacek
