### ISSUE TITLE
LuaGCS GUI

### ISSUE THREAD

**Issue by kniuk** [yaapu/FrskyLuaGCS#15]
When I edit parameter from lower table with "range editor" I type new "increment" value and the default action for Enter key is "Remove" IMHO default action of "Save" would be much better. 
![Zrzut ekranu 2020-12-11 235435](https://user-images.githubusercontent.com/57300765/101964473-cf011f80-3c11-11eb-8bd2-6a991fc95fda.png)
P.S. Example is not the best as this parameter should either 0 or 1

**Comment by yaapu** [comment]
makes sense, thanks

**Comment by yaapu** [comment]
fixed
