### ISSUE TITLE
Add Compass calibration

### ISSUE THREAD

**Issue by alteman** [yaapu/FrskyLuaGCS#16]
Currently only AS calibration is supported..
Something like ` {"CALIBRATE"  , {"Compass", "Airspeed and Baro"}, { {0,1}, {0,0,1} }, cmd_id=241, value=1 },` in plane_commands_1.lua (probably also copter_commands..)
I assume luas are autogenerated, so I didn't make a PR..

**Comment by yaapu** [comment]
Hi compass calibrate is not possible, if it was it would have been there :-)
