### ISSUE TITLE
v1.02 Horus has references to \taranis subfolder and fails to start

### ISSUE THREAD

**Issue by kniuk** [yaapu/FrskyLuaGCS#17]
Hi, I guess topic name explains everything. I rolled back to 1.01 and scripts works again.

Regards,
Jacek

**Comment by kniuk** [comment]
My radio is Jumper T16 OTX 2.3.11

**Comment by kniuk** [comment]
@yaapu Could you please look into that ?

**Comment by yaapu** [comment]
you're right, looking into this issue asap

**Comment by yaapu** [comment]
should be fixed, sorry :-)
