### ISSUE TITLE
PIDS parameters not working with LuaCGS and Ardupilot 4.1

### ISSUE THREAD

**Issue by Alienix33** [yaapu/FrskyLuaGCS#20]
I updated my Matek H743 FC with Arduplane V4.1.0 dev version (latest on 4th july)
Now LuaCGS works except for roll and pitch PIDS parameters

On Arduplane 4.1.0  PIDS parameters change their name but it seems that LuaCGS script is looking for the old name

see screenshot here attached
![screen-2021-07-04-182529](https://user-images.githubusercontent.com/86925151/124393226-b1a0b980-dcf9-11eb-91d8-b0e711542987.jpg)
![screen-2021-07-04-182535](https://user-images.githubusercontent.com/86925151/124393234-b82f3100-dcf9-11eb-984c-378bafb46f4f.jpg)

**Comment by Hwurzburg** [comment]
here is some screens for the new plane params that should  work in Horus and Taranis....drop the ".txt" off and put in scripts/tools/yaapu folder...I adapted these from my radio (which has a bit more complext solution)
the param name change is causing some issues on getting an easy solution for both Plane 4.09 AND 4.1....but this will work, although not pretty...Alex and I are working on a solution...
[plane_params_2.lua.txt](https://github.com/yaapu/FrskyLuaGCS/files/6760555/plane_params_2.lua.txt)
[plane_params_3.lua.txt](https://github.com/yaapu/FrskyLuaGCS/files/6760556/plane_params_3.lua.txt)

**Comment by yaapu** [comment]
@Alienix33 please test the latest version, should be compatible with ArduPilot 4.1 beta PIDs

**Comment by Alienix33** [comment]
Thank Alex, I confirm that 
now with latest luaCGS version is works fine with ArduPilot 4.1 beta PIDs
 ![screen-2021-07-18-163645](https://user-images.githubusercontent.com/86925151/126071389-a6325c45-0f7e-41e8-a4ae-4bc2b40cab52.jpg)

Most of parameters are "ok" some are "rn"  what is the meaning ?

**Comment by yaapu** [comment]
Hi it means the ranges specified in the config file are too  narrow

**Comment by Hwurzburg** [comment]
Need to get the autotune algorithm finalized before adjusting the limit boundaries.. .not until stable 4.1

**Comment by Hwurzburg** [comment]
Use the ignore ranges feature until then...if it's now included?

**Comment by yaapu** [comment]
yes it's included, last page select ignore ranges (it's not sticky)
