### ISSUE TITLE
Feature request: Upload WP missions.

### ISSUE THREAD

**Issue by sher1ock** [yaapu/FrskyLuaGCS#26]
Being able to upload presaved waypoint missions would be a really useful addition to this. Not having to have an entire extra laptop with mission planner running just for uploading missions when everything else can be done on the RC.

**Comment by yaapu** [comment]
Hi, mission upload is a very big task, not so much for the script side but for the bandwidth requirements and ability to send a long packet sequence with guaranteed delivery, I don't think I will ever attempt such a feature

**Comment by yaapu** [comment]
will not do. sorry :-)
