### ISSUE TITLE
GCS does not work with EdgeTX

### ISSUE THREAD

**Issue by Harald69** [yaapu/FrskyLuaGCS#31]
Hello is it possible to make it also work for EdgeTX. It does only show a black screen

**Comment by xixijoe** [comment]
Yes, I have the same wish. My luaGCS works perfect on open tx.  It takes a long time to run on the 2.7edgetx， And does not work at all on the 2.8edgetx.  The display of The number digits does not show from the background.

**Comment by yaapu** [comment]
please retest with latest master

**Comment by xixijoe** [comment]
thank you alex, it is working now. but the cfg page does not. should all the model files need to convert from the tools or it can't be used from the previous version?

**Comment by yaapu** [comment]
Hi, copy the old files in the new cfg folder, should work just fine

**Comment by yaapu** [comment]
Hi, copy the old files in the new cfg folder, should work just fine

**Comment by xixijoe** [comment]
yes. you are right. I did not notice they are different route from OpenTX. thank you for all your great work. I enjoy it

**Comment by yaapu** [comment]
> yes. you are right. I did not notice they are different route from OpenTX. thank you for all your great work. I enjoy it

thanks! the new version has a different filesystem layout for both OpenTX and EdgeTX
