### ISSUE TITLE
Yaapu not working with ACCST 2.0 RX TX frimware via Fport

### ISSUE THREAD

**Issue by HYC23** [yaapu/FrskyLuaGCS#33]
Hi,

I tried so hard with several settings to make the Matek H743 FC work with RXSR. Then, I downgraded the RX and TX to the old framework, everything worked well. 

I know it's highly unlikely to be an issue in the GCS code. However, I still want to confirm whether is my setting wrong (Serialx_options) for Fport or if the 2.0 firmware is unsupported.

Thanks for your help.

**Comment by yaapu** [comment]
sorry for the huge delay, you're right, true bidirectional support is really bound to fw quality, I've had issues with many tx/rx combos, I ended up sticking with what works :-)
