### ISSUE TITLE
GUI: difficult to remove options...and adding to end requires inputting desc first

### ISSUE THREAD

**Issue by Hwurzburg** [yaapu/FrskyLuaGCS#4]
use ARMING_CHECK as the test case...

make a list like this:
None 
ALL 
ALL but GPS (and GPS config)
ALL but INS
ALL but LOGGING

**Comment by Hwurzburg** [comment]
but damn close....two thumbs up!

**Comment by yaapu** [comment]
thanks Henry, agree and fixed in current release.
