### ISSUE TITLE
FrskyLuaGCS endless Loading

### ISSUE THREAD

**Issue by DarkSoulRL** [yaapu/FrskyLuaGCS#9]
Matek F405 CTR
R9mm Fport connected using "inverted Fport" pin https://ardupilot.org/copter/docs/common-FPort-receivers.html
Arduplane from https://github.com/yaapu/ardupilot/tree/frsky_telem_bidirectional

endless Loading:
https://www.youtube.com/watch?v=Et8wgduSBB0

**Comment by yaapu** [comment]
Hi, what version of OpenTX are you using?
I do have a T16 so I can try to reproduce your issue, most likely a firmware bug.
What R9 firmware version? I do all my testing with latest flex but not on ACCESS firmware.

**Comment by DarkSoulRL** [comment]
Hello!
Last  stable official OpenTX 2.3.7
![image](https://user-images.githubusercontent.com/21101416/83387847-7baa4b00-a3fe-11ea-87a8-f3c319576de6.png)

**Comment by DarkSoulRL** [comment]
R9mm fport firmware  2019-11-01 | 190201 R9_MM_FLEX_Fport.frk

R9M 2019 fport firmware 2019-02-13 | 190117  R9M_FLEX.frk

**Comment by yaapu** [comment]
it's an r9mm-ota?

**Comment by DarkSoulRL** [comment]
yes, r9mm-ota, ACCST FIRMWARE

**Comment by yaapu** [comment]
Hi, does RC input work? can you connect to the console with mavproxy or mission planner and check messages, do you get rc fail or failsafes?

**Comment by DarkSoulRL** [comment]
RC link work fine, but on T16 i have only  GPS, RSSI, RxBt  telemetry.
Yesterday I flew 3 km, without any problems.

**Comment by DarkSoulRL** [comment]
![image](https://user-images.githubusercontent.com/21101416/83410414-6dbcf000-a427-11ea-80dc-2df9067beb77.png)

**Comment by yaapu** [comment]
what are your serial_options, rc_options and brd_alt_config params?

**Comment by DarkSoulRL** [comment]
serial5_options = 4 (halfDuplex)
rc_options = 0
brd_alt_config = 1

**Comment by yaapu** [comment]
looks correct, I don't have neither your board nor your receiver, I'm 100% positive it works with external inverters for I've done extensive testing, on r9mm and r-xsr receivers in ACCST 1.x .

I have an f405-Wing on my bench which does not work as expected with brd_alt_config=1, serial7_options=4 on my r-xsr using the uninverted pad, so there is something when using receivers supporting uninverted signals

**Comment by DarkSoulRL** [comment]
Ok, I’ll try to use an external inverter, but I don’t have one now, unfortunately.
Will you fix this problem?

**Comment by yaapu** [comment]
I'll try :-) it's in the way ardupilot handles serial ports it's not in the frsky library code nor in the lua gcs

**Comment by Hwurzburg** [comment]
MatekF405  only work for Sport on a UART if an external bi-directional inverter is used....see https://ardupilot.org/plane/docs/common-frsky-telemetry.html

**Comment by Hwurzburg** [comment]
things to check:
using the "inverted Fport" pin from RX not FPort pin connected to UART2TX....I dont think that BRD_ALT_CONFIG is required...TX pin always there...but should not hurt...SERIAL5 port params look okay...if this is still an issue a bug report should be entered in ArduPilot....
what is a little strange in the Mavproxy connection is that FPort RC is not being reported...it should have the GCS message if SBUS or FPORT or other serial RC protocols are being detected

**Comment by Hwurzburg** [comment]
Alex, if you are having the same issue, then we need to file a bug report in ArduPilot....I have never used the inverted Fport or Sport pins on a RX myself, but Tridge has tested on a few boards...

**Comment by yaapu** [comment]
Henry I'm doing lots of testing to isolate the cases I think should work but don't using a MatekF405Wing and a KakuteF7

**Comment by yaapu** [comment]
For instance on a kakute F7 with brd_alt_config=0, serial6_protocol=23, serial6_options=7,rc_options=0 using the inverted fport pad on my r-xsr, rc+passthrough telemetry works but as soon as I start sending bidirectional telemetry frames I get RC Fails/rc cleared every once in a while, same thing happens on the MatekF405-Wing if I enable half duplex without inversion with SERIAL_OPTIONS=4

**Comment by DarkSoulRL** [comment]
> things to check:
> using the "inverted Fport" pin from RX not FPort pin connected to UART2TX....I dont think that BRD_ALT_CONFIG is required...TX pin always there...but should not hurt...SERIAL5 port params look okay...if this is still an issue a bug report should be entered in ArduPilot....
> what is a little strange in the Mavproxy connection is that FPort RC is not being reported...it should have the GCS message if SBUS or FPORT or other serial RC protocols are being detected

Checked on serial2. It behaves exactly the same as on serial5 + BRD_ALT_CONFIG = 1
